######################
# Yaml related hooks
# These only have shell dependencies
- id: vars-in-variables-files
  name: "Ensure that all variables are defined in files that have the following name format: `variables[.grouping].tf`"
  description: "Errors if a variable is defined in a file that does not start with `variables.`"
  entry: hooks/vars-in-variables-files/check
  language: script
  files: \.tf$
  exclude: ^variables\..*\.tf$
  ######################
