- id: vars-in-variables-files
  name: "Ensure variables are in `variables[.grouping].tf`"
  description: "Errors if a variable is defined in a file that does not start with `variables.`"
  entry: hooks/vars-in-variables-files/check
  language: script
  files: \.tf$
  exclude: ^variables\..*\.tf$

- id: outputs-in-outputs-files
  name: "Ensure outputs are in `outputs[.grouping].tf`"
  description: "Errors if a outputs is defined in a file that does not start with `outputs.`"
  entry: hooks/outputs-in-outputs-files/check
  language: script
  files: \.tf$
  exclude: ^outputs\..*\.tf$
