#!/bin/bash -e

REPO_DIR="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)")"

# Find all files in the hooks directory and its subdirectories
find "$REPO_DIR/hooks" -type f | while read -r file; do
	# If the file is a test script, execute it
	if [[ "$file" == *"/test" ]]; then
		"$file"
	fi
done
